### PR TITLE
Fix Tekton variable substitution

### PR DESCRIPTION
**Pull request by lcarva**

### CODE REVIEW

**Comment by lcarva** [comment]
I can't find a way to configure the shell parser to not include the space, so I opted to just fixing up the generated script.

**Comment by lcarva** [comment]
I tested this against the build-definitions repo and it looks like it does the right thing:

```diff
diff --git a/task/buildah-oci-ta/0.1/buildah-oci-ta.yaml b/task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
index fb349fa..65f856f 100644
--- a/task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
+++ b/task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
@@ -324,7 +324,7 @@ spec:
         touch $(results.BASE_IMAGES_DIGESTS.path)
         for image in $BASE_IMAGES; do
           if [ "${image}" != "scratch" ]; then
-            buildah images --format '{{ .Name }}:{{ .Tag }}@{{ .Digest }}' --filter reference="$image" >>$( results.BASE_IMAGES_DIGESTS.path)
+            buildah images --format '{{ .Name }}:{{ .Tag }}@{{ .Digest }}' --filter reference="$image" >>$(results.BASE_IMAGES_DIGESTS.path)
           fi
         done
 
diff --git a/task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml b/task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
index b7c05ab..2f09a3a 100644
--- a/task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
+++ b/task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
@@ -234,8 +234,8 @@ spec:
         if [ "${EXIT_CODE}" != 0 ]; then
           exit "${EXIT_CODE}"
         fi
-        printf "%s" "${RESULT_SHA}" >"$( results.commit.path)"
-        printf "%s" "${PARAM_URL}" >"$( results.url.path)"
+        printf "%s" "${RESULT_SHA}" >"$(results.commit.path)"
+        printf "%s" "${PARAM_URL}" >"$(results.url.path)"
 
         if [ "${PARAM_FETCH_TAGS}" = "true" ]; then
           echo "Fetching tags"

```

**Review by zregvart — APPROVED** [review]
This is similar to what I would opt to do for the simplest fix. Make sure to update the ta.yaml files in golden directory

**Review by simonbaird — APPROVED** [review]
Nice.

**Pull request merged**
